/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.studentaide.Class1;

import java.awt.Toolkit;

/**
 *
 * @author Tarpan
 */
public class EnvironmentalScience1_1 extends javax.swing.JFrame {

    /**
     * Creates new form EnvironmentalScience1
     */
    public EnvironmentalScience1_1() {
        initComponents();
        A();
        EVS1_SP1.getVerticalScrollBar().setUnitIncrement(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EVS1_SP1 = new javax.swing.JScrollPane();
        EVS1_IMG1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chapter 1 - Mode of Transport ");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EVS1_SP1.setBackground(new java.awt.Color(255, 255, 255));

        EVS1_IMG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EVS1_IMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studentaide/Class1/EVS1_Ch1.png"))); // NOI18N
        EVS1_IMG1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EVS1_SP1.setViewportView(EVS1_IMG1);

        getContentPane().add(EVS1_SP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvironmentalScience1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvironmentalScience1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvironmentalScience1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvironmentalScience1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnvironmentalScience1_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EVS1_IMG1;
    private javax.swing.JScrollPane EVS1_SP1;
    // End of variables declaration//GEN-END:variables

    private void A() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Project_Icon.png"))); //To change body of generated methods, choose Tools | Templates.
    }
}
